### ISSUE TITLE
super() on abstract class

### ISSUE THREAD

**Issue by kampiamodikuesto** [BrijeshSaxena/design-pattern-command#1]
Hi, i can't understand why use super() on abstract command, without it all things aren't the same? isn't it redundant?

"super calls the parent class' constructor with the arguments passed to it. In this case, super() calls the parent's no-arg constructor. A class that doesn't explicitly declare its parent implicitly extends Object, so here super() will call Object's default constructor, which it would also do implicitly had the call been omitted. So it's not wrong, just redundant." [link](https://stackoverflow.com/questions/13472904/difference-between-structural-design-pattern-and-behavioral-design-pattern)

**Comment by BrijeshSaxena** [comment]
@kampiamodikuesto , its seems like redundant. But, for me its explicit way of invoking parent's default constructor. Here by "explicit", I am only showing my intention of getting the "default" behavior of parent's instance and indicating customization by no-arg of Command. Never mind. just o avoid confusion, I have removed "super" from abstract command class. I hope now you could focus on the pattern and not super.
Also, I have enhanced the code little more. Have an update please.
